### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by navarr** [Shotbow/ChatBot#66]
```
5/30/2020 4:09:38 AM(node:30) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send messages to this user
5/30/2020 4:09:38 AM    at /usr/src/app/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65
5/30/2020 4:09:38 AM    at /usr/src/app/node_modules/snekfetch/src/index.js:215:21
5/30/2020 4:09:38 AM    at runMicrotasks (<anonymous>)
5/30/2020 4:09:38 AM    at processTicksAndRejections (internal/process/task_queues.js:97:5)
5/30/2020 4:09:38 AM(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
5/30/2020 4:09:38 AM(node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by McJeffr** [comment]
Has this error occurred again recently? It could have been patched by v12 or the new command handler.

**Comment by navarr** [comment]
It has not occurred in the past two days.  I'll close this ticket for now.
